### ISSUE TITLE
Failed to load the indent-guide-improved package

### ISSUE THREAD

**Issue by benshrimpton** [harai/indent-guide-improved#20]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [indent-guide-improved](https://github.com/harai/indent-guide-improved) package, v1.4.2

### Stack Trace

Failed to load the indent-guide-improved package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/benshrimpton/.atom/packages/indent-guide-improved-master/lib/indent-guide-improved.coffee:2:5)
  at Object.<anonymous> (/Users/benshrimpton/.atom/packages/indent-guide-improved-master/lib/indent-guide-improved.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:759:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:670:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:96:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by krystiancharubin** [comment]
Reinstalling the plugin fixes the issue
