### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pixelPositionForScreenPosition' of null

### ISSUE THREAD

**Issue by VAdamec** [harai/indent-guide-improved#26]
[Enter steps to reproduce below:]

1. Just push to Git repo

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [indent-guide-improved](https://github.com/harai/indent-guide-improved) package, v1.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForScreenPosition' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:279

TypeError: Cannot read property 'pixelPositionForScreenPosition' of null
  at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:279:28)
  at updateGuide (/Users/adamecv/.atom/packages/indent-guide-improved/lib/indent-guide-improved.coffee:22:36)
  at up (/Users/adamecv/.atom/packages/indent-guide-improved/lib/indent-guide-improved.coffee:58:9)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at maxDelayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7714:9)

```

### Commands

```
     -1:46.2.0 tree-view:move (span.name.icon.icon-file-text)
     -1:44.8.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -1:44.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:41.7.0 tree-view:move (span.name.icon.icon-file-text)
     -1:40.3.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -1:40 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:08.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -0:31.5.0 git-plus:add-all-commit-and-push (atom-text-editor.editor.is-focused)
  8x -0:29 core:backspace (atom-text-editor.editor.is-focused)
     -0:13.5.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:13.2.0 core:delete (atom-text-editor.editor.is-focused)
     -0:10.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:delete (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/adamecv/workspace",
    "followSymlinks": true,
    "disabledPackages": [
      "symbols-view",
      "jenkins",
      "atom-terminal-panel"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-ctags, v4.4.0
autocomplete-php, v0.3.7
autocomplete-ruby, v0.1.0
clipboard-plus, v0.5.1
coffee-navigator, v0.0.16
formatter-coffeescript, v0.1.1
git-log, v0.4.1
git-plus, v5.4.7
imdone-atom, v1.1.53
indent-guide-improved, v1.4.3
language-puppet, v0.15.0
linter, v1.10.0
linter-coffeelint, v1.1.2
linter-js-yaml, v1.2.0
linter-php, v1.0.5
linter-puppet, v1.0.0
linter-pylint, v1.0.3
linter-ruby, v1.2.0
linter-shellcheck, v1.0.2
make-coffee, v0.1.1
minimap, v4.16.0
seti-icons, v0.4.5
seti-syntax, v0.4.1
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
same here

**Comment by whmountains** [comment]
Happened to me too, but it my case it was triggered by closing an unsaved tab while in zen mode.  It went something like this:

* I'm in zen mode
* I edit a a markdown document, then hit CMD-W to close it.
* atom asks me if I want to save the unsaved changes, and I chose "save"
* atom saves and closes the file and shows me the next open tab while staying in zen mode (also incidentally another markdown document where indent guides aren't even needed)
* the error is immediately thrown

**Comment by Maelstrome26** [comment]
I got this just by pressing "Close all Tabs".

**Comment by harai** [comment]
I think this fixes the problem.

**Comment by VAdamec** [comment]
Still occuting

**Comment by VAdamec** [comment]
[Enter steps to reproduce below:]

1. GIT PUSH

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [indent-guide-improved](https://github.com/harai/indent-guide-improved) package, v1.4.4


### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForScreenPosition' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:321

TypeError: Cannot read property 'pixelPositionForScreenPosition' of null
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:321:28)
    at updateGuide (/Users/adamecv/.atom/packages/indent-guide-improved/lib/indent-guide-improved.coffee:23:36)
    at up (/Users/adamecv/.atom/packages/indent-guide-improved/lib/indent-guide-improved.coffee:59:9)
    at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
    at maxDelayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7714:9)
```

### Commands

```
     -0:25 core:paste (atom-text-editor.editor.is-focused)
     -0:24.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:23 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:22.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:22.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:18 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:17.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:12.1.0 git-plus:add-all-commit-and-push (atom-text-editor.editor.is-focused)
     -0:11.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:10.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:09.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:08.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/adamecv/workspace",
    "followSymlinks": true,
    "disabledPackages": [
      "symbols-view",
      "jenkins",
      "atom-terminal-panel"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-ctags, v4.4.1
autocomplete-php, v0.3.7
autocomplete-python, v0.10.4
autocomplete-ruby, v0.1.0
clipboard-plus, v0.5.1
coffee-navigator, v0.0.16
formatter-coffeescript, v0.1.1
git-log, v0.4.1
git-plus, v5.6.6
imdone-atom, v1.2.7
indent-guide-improved, v1.4.4
language-puppet, v0.15.0
linter, v1.11.2
linter-coffeelint, v1.1.2
linter-js-yaml, v1.2.4
linter-puppet, v1.0.0
linter-pylint, v1.0.5
linter-ruby, v1.2.0
linter-shellcheck, v1.0.2
make-coffee, v0.1.1
minimap, v4.16.2
seti-icons, v0.4.5
seti-syntax, v0.4.1
seti-ui, v0.8.1

# Dev
No dev packages
```
