### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by Stanzilla** [harai/indent-guide-improved#28]
[Enter steps to reproduce below:]

1. ... Happened right on launching Atom

**Atom Version**: 1.3.0-beta0
**System**: Microsoft Windows 8.1 Pro with Media Center
**Thrown From**: [indent-guide-improved](https://github.com/harai/indent-guide-improved) package, v1.4.3

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At C:\Users\Benjamin\.atom\packages\indent-guide-improved\lib\indent-guide-improved.coffee:29

TypeError: Cannot read property '0' of null
    at updateGuide (C:\Users\Benjamin\.atom\packages\indent-guide-improved\lib\indent-guide-improved.coffee:29:97)
    at up (C:\Users\Benjamin\.atom\packages\indent-guide-improved\lib\indent-guide-improved.coffee:57:20)
    at debounced (C:\Users\Benjamin\AppData\Local\atom\app-1.3.0-beta0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7737:27)
    at Emitter.module.exports.Emitter.emit (C:\Users\Benjamin\AppData\Local\atom\app-1.3.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\Benjamin\AppData\Local\atom\app-1.3.0-beta0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1314:25
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "highlight-css-color",
      "white-cursor",
      "feedback",
      "welcome",
      "auto-indent",
      "atom-format-lua",
      "build-gulp"
    ],
    "excludeVcsIgnoredPaths": false,
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "one-dark-vivid-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-sass, v0.1.0
build, v0.48.0
css-color-underline, v1.0.1
file-icons, v1.6.11
file-watcher, v0.4.0
fold-functions, v0.4.3
indent-guide-improved, v1.4.3
indentation-indicator, v0.6.0
keyboard-localization, v1.4.10
language-batch, v0.3.3
language-blade, v0.16.0
language-dots, v0.0.4
language-lua, v0.9.4
language-powershell, v2.1.0
laravel, v0.7.0
less-than-slash, v0.11.0
line-ending-selector, v0.3.0
linter, v1.10.0
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-luacheck, v1.1.3
linter-php, v1.1.1
minimap, v4.16.0
one-dark-vivid-syntax, v1.1.1
open-recent, v4.0.1
revert-buffer, v0.5.0
svn, v0.0.8
synced-sidebar, v0.4.2
tabs-to-spaces, v0.11.1
tidy-tabs, v0.3.0
tool-bar, v0.1.9
tool-bar-main, v0.0.8
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by Stanzilla** [comment]
Might be fixed by https://github.com/atom/atom/commit/fa66048d71d4edcc6f066075f2ee649a220e2e7b will report back when it is..

**Comment by derEremit** [comment]
same on ubuntu 14.04 with beta 1.3.0

**Comment by NathNioche** [comment]
Same on windows 8

**Comment by amosshapira** [comment]
Same on OS X 10.11.2 El Capitan

**Comment by polarathene** [comment]
Just updated atom and ran into this bug. Updated packages and this package was still throwing an error so I disabled it, code pane was still messed up, restarted atom, enabled this package and it's working fine now.

Windows 8.1x64
