### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by Stanzilla** [harai/indent-guide-improved#64]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Pro with Media Center
**Thrown From**: [indent-guide-improved](https://github.com/harai/indent-guide-improved) package 1.4.12

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At C:\Users\Benjamin\AppData\Local\atom\app-1.19.0-beta0\resources\app\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/text-buffer/lib/display-layer.js:333:17)
    at DisplayLayer.clipScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/text-buffer/lib/display-layer.js:391:18)
    at TextEditor.module.exports.TextEditor.clipScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor.js:1793:38)
    at HTMLElement.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-element.js:242:38)
    at updateGuide (/packages/indent-guide-improved/lib/indent-guide-improved.coffee:17:36)
    at up (/packages/indent-guide-improved/lib/indent-guide-improved.coffee:51:9)
    at debounced (/packages/indent-guide-improved/node_modules/lodash/index.js:7737:27)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1570:26)
    at later (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/text-buffer/lib/helpers.js:21:13)
```

### Commands

```
     -0:12 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-increment 0.3.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
auto-detect-indentation 1.3.0 
autocomplete-html-entities 0.1.0 
autocomplete-php 0.3.7 
color-picker 2.2.5 
editorconfig 2.2.2 
file-icons 2.1.7 
file-watcher 1.1.0 
indent-guide-improved 1.4.12 
intentions 1.1.2 
language-batch 0.4.0 
language-blade 0.31.0 
language-cmake 0.3.0 
language-dots 0.0.4 
language-lua 0.9.11 
language-lua-wow 0.2.0 
language-powershell 4.0.0 
language-toc-wow 0.2.0 
less-than-slash 0.16.0 
linter 2.1.4 
linter-luacheck 2.0.1 
linter-php 1.3.2 
linter-ui-default 1.6.1 
linter-xo 0.23.0 
MagicPython 1.0.10 
markdown-scroll-sync 2.1.2 
minimap 4.28.2 
one-dark-vivid-syntax 1.7.1 
pigments 0.39.1 
pretty-json 1.6.3 
project-plus 1.0.0 
revert-buffer 0.5.0 
sort-lines 0.14.0 
space-tab 0.4.2 
sync-settings 0.8.2 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
trailing-spaces 0.4.0 
```

**Comment by Positive07** [comment]
Replicated, Windows 10 x64 Atom 1.19 beta 0

This happened when I opened Atom

**Comment by Evpok** [comment]
Replicated on KDE Neon/Ubuntu Zesty Atom 1.19 beta 0

**Comment by danielbayley** [comment]
Also on:
macOS: Sierra 10.12.5
Atom: 1.19.0-beta0 x64
indent-guide-improved: 1.4.12

**Comment by douglascamata** [comment]
This problem still happens for me. Running Atom 1.19 and indent-guide-improved 1.4.13.
