### ISSUE TITLE
Failet to activate the indent-guide-improved package atom v1.19.0-beta0

### ISSUE THREAD

**Issue by Eldair** [harai/indent-guide-improved#66]
**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [indent-guide-improved](https://github.com/harai/indent-guide-improved) package 1.4.12

### Stack Trace

Failed to activate the indent-guide-improved package

```
At Invalid Point: (NaN, 0)

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/text-buffer/lib/display-layer.js:333:17)
    at DisplayLayer.clipScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/text-buffer/lib/display-layer.js:391:18)
    at TextEditor.module.exports.TextEditor.clipScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor.js:1793:38)
    at HTMLElement.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-element.js:242:38)
    at updateGuide (/packages/indent-guide-improved/lib/indent-guide-improved.coffee:17:36)
    at /packages/indent-guide-improved/lib/indent-guide-improved.coffee:79:7
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/workspace.js:717:15)
    at Object.activate (/packages/indent-guide-improved/lib/indent-guide-improved.coffee:74:20)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:16.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
aesthetic-ui 4.0.0 
an-old-hope-syntax 1.0.4 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.1 
atom-dark-fusion-syntax 2.2.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-minify 0.8.0 
atom-wrap-in-tag 0.6.0 
auto-indent 0.5.0 
busy-signal 1.4.3 
change-case 0.6.5 
color-picker 2.2.5 
docblockr 0.10.3 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.1.7 
firewatch-syntax 1.1.1 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
icon-fonts 2.16.2 
indent-guide-improved 1.4.12 
intentions 1.1.2 
isotope-ui 2.8.5 
jquery-snippets 11.0.0 
js-hyperclick 1.11.0 
language-babel 2.66.0 
language-blade 0.31.0 
language-vue 0.23.0 
laravel 0.7.1 
laravel-forms-bootstrap-snippets 1.2.0 
linter 2.2.0 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-jshint 3.1.2 
linter-php 1.3.2 
linter-phpcs 1.6.6 
linter-phpmd 1.5.3 
linter-stylelint 3.10.0 
linter-ui-default 1.6.1 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-dark-atom-syntax 2.1.0 
northem-dark-atom-ui 2.1.0 
nova-atom-syntax 1.4.1 
nova-atom-ui 1.3.0 
open-recent 5.0.0 
php-cs-fixer 4.1.0 
php-fmt 0.1.2 
pigments 0.39.1 
prettier-atom 0.33.0 
sass-autocompile 0.13.3 
seti-syntax 1.1.3 
seti-ui 1.8.0 
stylefmt 5.0.1 
sync-settings 0.8.2 
text-manipulation 0.6.0 
todo-show 1.11.0 
vue-hyperclick 0.2.0 
webbox-color 0.5.9 
```

**Comment by eldair** [comment]
1.4.13 fixes the issue, thanks!
